Update deploy_pipeline.yml

diff --git a/.github/workflows/deploy_pipeline.yml b/.github/workflows/deploy_pipeline.yml
--- a/.github/workflows/deploy_pipeline.yml
+++ b/.github/workflows/deploy_pipeline.yml
@@ -26,7 +26,15 @@ jobs:
         uses: Snowflake-Labs/snowflake-cli-action@v1.5
         with:
           cli-version: "latest"
-          default-config-file-path: "snowflake/config.toml"
+          default-config-file-path: ".snowflake/config.toml"
+
+      - name: Validate Snowflake configuration
+        run: |
+          snow conn test
+          if [ $? -ne 0 ]; then
+            echo "Snowflake connection configuration failed."
+            exit 1
+          fi
 
       - name: Fetch repository changes
         run: snow git fetch SF_DE
